const sidebar_width = 100;
var image_open = false;
const data = {
    'sgl': {
        'project': 'Stargate Studios Library',
        'type': 'website',
        'description': "This site was originally built 10 years ago, and it was barely usable. It took over 10 seconds to load the page and anywhere between 15-30 seconds to finish loading the search results. This stemmed from a poorly designed SQL database, which I restructured to allow for more efficient queries.<br><br>I've touched every other aspect of the codebase since I embarked on this project in June 2023, rethinking the architecture of the entire codebase, removing security vulnerabilities, modernizing the look of the site, improving frontend javascript performance, and optimizing the workflow with Python and bash scripts. It's come a long way in terms of reliability and usability since I started on it, and Stargate Studios' employees and clients are now actively using the site as a convenient way to access the company's vast stock footage library.",
        'tags': ['MySQL','jQuery','Backbone','node.js','HTML','CSS','Python','Bash'],
        'url': 'http://library.stargatestudios.net/',
        'links': [
            {
                'title': 'logging software to add new clips to the library (currently a work-in-progress)',
                'link': 'logger.webp' 
            }]
    },
    'sgc': {
        'project': 'Stargate PanoCam',
        'type': 'desktop app',
        'description': 'Stargate Studios initially brought me on as a developer to build them a camera control app. The company shoots virtual production plates using 9 or more cameras simultaneously, all of which are mounted to a car, and without a way to control all the cameras at once, a camera person would have to get out of the car to adjust the settings on each camera. This was not only slow, but also error-prone and sometimes unsafe.<br><br>In just two months, I built out the core functionality of the app, allowing an operator to connect and disconnect multiple cameras and to adjust all relevant camera settings. Since then, I’ve added major features, such as the ability to log details of the shoot, along with GPS tracking to map the driver\'s exact route. These features are crucial for keeping these shoots organized amongst the company’s 300,000+ clip library.<br><br>We use Sony cameras for our plate shoots, and we\'ve worked alongside the Sony team to implement the features we needed for this app. I even flew to Japan in 2022 to meet their developer team and discuss the Sony SDK codebase and upcoming features. ',
        'tags': ['C++', 'wxWidgets', 'Bash'],
        'links': [
            {
                'title': 'a photo of the cameras on the camera car',
                'link': 'car_rig.webp'
            },
            {
                'title': 'output report generated by this app',
                'link': 'camera-report.html' 
            },
            {
                'title': 'a group shot of us with the Sony team in Shibuya, Tokyo',
                'link': 'sony_team.webp'
            }]
    },
    'eas': {
        'project': 'European Auto Service',
        'type': 'website',
        'description': "For a freelance job, I built this simple website using Wordpress—which was a requirement of the client's, so they could make small changes on their own without the need for a developer.<br><br>I stayed on top of deadlines and managed the client's expectations, keeping them abreast of progress, and ultimately delivered a site with which they were very satisfied.",
        'tags': ['jQuery','HTML','CSS','Wordpress'],
        'url': 'https://www.europeanautoreseda.com/'
    },
    'ksj': {
        'project': 'Karine Sultan Jewelry',
        'type': 'website',
        'description': "I redesigned multiple aspects of this website, changing its look and adding new features. I also wrote software that allowed the employees to make a specific set of changes to the underlying database.",
        'tags': ['MySQL','javascript','HTML','CSS','Shopify'],
        'url': 'https://www.karinesultan.com/'
    },
}
const tag_colors = {
    'MySQL': [61,110,148],
    'jQuery': [9,105,173],
    'javascript': [168,21,21],
    'Backbone': [74,112,192],
    'node.js': [131,205,42],
    'HTML': [220,74,37],
    'CSS': [37,75,222],
    'Python': [247,201,63],
    'Bash': [177,59,145],
    'Shopify': [149,191,71],
    'Wordpress': [0,0,0]
}
var img_overlay;
function resizeCalc() {
    const fontSize = window.innerWidth / 703 + 'em';
    document.querySelectorAll('.overlay-text').forEach(element => {
        element.style.fontSize = fontSize;
    });
}
function throttle(func, limit) {
    let inThrottle;
    return function() {
        const args = arguments;
        const context = this;
        if (!inThrottle) {
            func.apply(context, args);
            inThrottle = true;
            setTimeout(() => inThrottle = false, limit);
        }
    }
}
async function preloadImage(url) {
    var img = new Image();
    img.src = url;
}
for (element in data) {
    preloadImage('img/'+element+'.webp');
}
document.addEventListener('DOMContentLoaded', function(event) { 
    var html = '';
    for (element in data) {
        html += '<div class="example" style="background-image:url(\'img/'+element+'.webp\')" onclick="click_example(\''+element+'\')"><div class="overlay"><div class="overlay-text"><span class="overlay-type">'+data[element]['type']+': </span>'+data[element]['project']+'</div></div></div>';
    }
    document.getElementById('portfolio-list').innerHTML = html;
    window.addEventListener('resize', throttle(function() {
        resizeCalc();
    }, 100));
    document.getElementById('sidebar').style.width = sidebar_width+'%';
    document.getElementById('sidebar').style.right = '-'+sidebar_width+'%';
    resizeCalc();
    addEventListener("keyup", (event) => {
        if (event.key == 'Escape') {
            if (image_open) {
                close_image();
            } else {
                close_sidebar();
            }
        }
    });
    img_overlay = document.querySelector("#img-overlay");
});
var sidebar_open = false;
var current_example = null;
function click_example(id) {
    if (sidebar_open) {
        if (current_example == id) {
            close_sidebar();
        } else {
            load_sidebar(id);
        }
    } else {
        load_sidebar(id);
        open_sidebar();
    }
    current_example = id;
}
function load_sidebar(id) {
    document.querySelector('#sidebar-title>span').innerHTML = data[id]['project'];
    document.getElementById('sidebar-description').innerHTML = data[id]['description'];
    if (data[id]['url']) {
        document.getElementById('visit-site').onclick = function(){window.open(data[id]['url'], '_blank').focus()};
        document.getElementById('visit-site').style.display = 'block';
    } else {
        document.getElementById('visit-site').style.display = 'none';
    }
    if (document.querySelectorAll('.gallery')) {
        document.querySelectorAll('.gallery').forEach(element => {
            element.remove();
        });
    }
    if (data[id]['links']) {
        data[id]['links'].forEach(link => {
            var html = ''
            var gallery = document.createElement('div');
            gallery.classList.add('box');
            gallery.classList.add('gallery');
            if (link['link'].endsWith('.html')) {
                html = '<a href="'+link['link']+'" target="_blank">'+link['title']+'</a>';
            } else if (link['link'].endsWith('.webp')) {
                html = '<a onclick="open_image(\''+link['link']+'\',\''+link['title']+'\')">'+link['title']+'</a>';
            }
            gallery.innerHTML = html;
            document.getElementById('box-container').appendChild(gallery);
        });
    }
    var tag_html = '';
    data[id]['tags'].forEach(tag => {
        var font_color = '#efefef';
        var rgb_bkgd = '210,105,3'
        if (tag_colors[tag]) {
            rgb_bkgd = tag_colors[tag].toString();
            if( tag_colors[tag][0]*0.299 + tag_colors[tag][1]*0.587 + tag_colors[tag][2]*0.114 > 136) {
                font_color = '#101010';
            }
        }
        tag_html += '<div style="color:'+font_color+';background:rgb('+rgb_bkgd+')">'+tag+'</div>'
    });
    document.getElementById('tags').innerHTML = tag_html;
    document.getElementById('thumb').style.backgroundImage = 'url(img/'+id+'.webp)';
}
function open_sidebar() {
    sidebar_open = true;
    document.getElementById('portfolio-list').style.marginRight = sidebar_width+'%';
    document.getElementById('sidebar').style.right = '0';
    document.getElementById('sidebar').style.boxShadow = '0 0 24px 5px #0000007a';
}
function close_sidebar() {
    sidebar_open = false;
    document.getElementById('portfolio-list').style.marginRight = '0';
    document.getElementById('sidebar').style.right = '-'+sidebar_width+'%';
    document.getElementById('sidebar').style.boxShadow = 'none';
}
function open_image(img, description) {
    if (!img) {
        document.querySelector('#img-overlay img').src = 'img/'+current_example+'.webp';
        document.querySelector('#img-overlay span').textContent = 'screenshot of project';
    } else {
        document.querySelector('#img-overlay img').src = 'img/'+img;
        document.querySelector('#img-overlay span').textContent = description;
    }
    document.getElementById('img-overlay').style.display = 'block';
    const grey_keyframes = [
        { opacity: "0%" },
        { opacity: "100%" }
        ];
    img_overlay.animate(grey_keyframes, 200);
    image_open = true;
}
function close_image() {
    const grey_keyframes = [
        { opacity: "100%" },
        { opacity: "0%" }
        ];
    const animation = img_overlay.animate(grey_keyframes, 200);
    animation.onfinish = () => {
        document.getElementById('img-overlay').style.display = 'none';
    };
    image_open = false;
}